version: '3.9'

services:
  app:
    container_name: django-web
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - ./.env
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    command: sh -c "/scripts/run_dev_server.sh"
    depends_on:
      - db

  
  db:
    image: postgres:13-alpine
    container_name: django-database
    volumes:
      - ./data:/var/lib/postgresql/data
    env_file:
      - ./.env
